version: '3.3'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
      - 80:80
      - 81:81
    volumes:
      - ./nginx_logs:/nginx_logs
    labels:
      com.datadoghq.ad.check_names: '["nginx"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: >-
        [{
          "nginx_status_url": "http://%%host%%:81/nginx_status/",
          "log_requests": "true"
        }]
      com.datadoghq.ad.logs: >-
        [
            {
            "type": "file",
            "source": "nginx",
            "service": "nginx",
            "path": "/nginx_logs/access.log",
            "log_processing_rules": [{
              "type": "multi_line",
              "name": "access_log",
              "pattern": "[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}"
            }]
          },
          {
            "type": "file",
            "source": "nginx",
            "service": "nginx",
            "path": "/nginx_logs/error.log",
            "log_processing_rules": [{
              "type": "multi_line",
              "name": "error_log",
              "pattern": "[0-9]{4}/[0-9]{2}/[0-9]{2}"
            }]
          }
        ]

  datadog-agent:
    image: datadog/agent:7.26.0-jmx
    env_file:
      - ./datadog.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /opt/datadog-agent/run:/opt/datadog-agent/run:rw
      - ./nginx_logs:/nginx_logs
